services:
  backend:
    build:
      context: ./backend

    container_name: servicehub-backend

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app
      - /app/node_modules

    restart: unless-stopped

    depends_on:
      - mongo

  mongo:
    image: mongo:8

    container_name: servicehub-mongo

    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
